import React from 'react';
import './styles/Body.css';
import demo from '../images/demo.gif'

function Body() {
  return (
    <div className='body'>
      <div className='text_container'>
        <h1>The Motivation</h1>
        <p>We ♥️ GraphQL! It reduces issues like over fetching and under fetching, making your data loading faster and improving user experience on slow and mobile connections. But the queries need to be precise- even adding an extra “s” to the query can give you completely different results. Popular GraphQL query-writing tools only work in a sandbox environment and do not allow you to test queries generated by the front-end code. You have to dive through your dev tools to troubleshoot any errors. That was until GraphErrQL!

</p>
        <h1>Why GraphErrQL?</h1>
        <p>
          GraphErrQL(Open Source) allows GraphQL developers to test queries created in
          sandbox AND live-listening modes and provides error feedback to assist
          in all stages of frontend query development. This easy-to-use npm
          package integrates into host applications and allows for improved data
          viewing and rapid development- all in a fun user interface!<br></br><br></br>
          GraphErrQL is an Open Source Product developed under tech accelerator OS Labs(opensourcelabs.io)
        </p>
      </div>
      <div className="demo_container">
        <h1>Here's GraphErrQL in action!</h1>
        </div>
        <div className="demo">
        <img src={demo} alt="demo" />
        </div>
      </div>
    
  );
}

export default Body;
