import React from 'react';
import './styles/Body.css';
import demo from '../images/demo.gif'

function Body() {
  return (
    <div className='body'>
      <div className='text_container'>
        <h1>The Motivation</h1>
        <p>We ♥️GraphQL! It reduces overfetching and underfetching, making your data loading faster and improving user experience on slow and mobile connections. But the queries need to be precise- adding an extra “s” can give you completely different results! Popular GraphQL query-writing tools only work in a sandbox environment and do not allow you to test queries generated by the front end code. You have to dive through your dev tools to troubleshoot any errors. Until GraphErrQL!
          
</p>
        <h1>Why GraphErrQl?</h1>
        <p>
          GraphErrQL allows GraphQL developers to test queries created in
          sandbox AND live-listening modes and provides error feedback to assist
          in all stages of frontend query development. This easy-to-use npm
          package integrates into host applications and allows for improved data
          viewing and rapid development- all in a fun user interface!
        </p>
      </div>
      <div className="demo_container">
        <h1>Check out this demo!</h1>
        </div>
        <div className="demo">
        <img src={demo} alt="demo" />
        </div>
      </div>
    
  );
}

export default Body;
